import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css" ;
import Link from "next/link";
import { Search, User, Package} from 'lucide-react'
import {auth} from "@/auth";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const session = await auth();
  
    return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > <div className="nav-bar">
          <div className="link-1">
            <Link href="/"><Package/>물물대여</Link>
          </div>
          <div className="link-2">
            <Link href="/listup">물건 둘러보기</Link>
            <Link href="/">내 물건</Link>
          </div>
          <div className="link-3">
            <Link href="/"><Search/></Link>
            {session ? (
              <span
                className="user-name">{sessionStorage.user?.name}님</span>
            ) : (
              <Link href="/login"><User/></Link>
            )}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
